export const FEED_SET_TYPE: "FEED_SET_TYPE" = "FEED_SET_TYPE";
export const FEED_FETCH_ORDERS: "FEED_FETCH_ORDERS" = "FEED_FETCH_ORDERS";
export const FEED_RECEIVE_ORDERS: "FEED_RECEIVE_ORDERS" = "FEED_RECEIVE_ORDERS";
export const FEED_CLEAR_ORDERS: "FEED_CLEAR_ORDERS" = "FEED_CLEAR_ORDERS";
