export const SET_BURGER_BUN: "SET_BURGER_BUN" = "SET_BURGER_BUN";
export const ADD_BURGER_PRODUCT: "ADD_BURGER_PRODUCT" = "ADD_BURGER_PRODUCT";
export const REMOVE_BURGER_PRODUCT: "REMOVE_BURGER_PRODUCT" =
  "REMOVE_BURGER_PRODUCT";
export const SWAP_BURGER_PRODUCTS: "SWAP_BURGER_PRODUCTS" =
  "SWAP_BURGER_PRODUCTS";
export const CLEAR_BURGER_PRODUCTS: "CLEAR_BURGER_PRODUCTS" =
  "CLEAR_BURGER_PRODUCTS";